spring.mvc.view.prefix=/WEF-INF/view/
spring.mvc.view.suffix=.jsp

server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/board?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=maria123

mybatis.mapper-locations:classpath:com/newlecture/web/dao/mybatis/mapper/*.xml
